DROP TABLE Logs
GO
CREATE TABLE Logs(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	Message VARCHAR(3000) NOT NULL,
	Level VARCHAR(10) NOT NULL,
	Source VARCHAR(300) NULL,
	Parameters VARCHAR(300) NULL,
	ErrorSeverity INT NULL,
	ErrorNumber INT NULL,
	ErrorState INT NULL,
	Exception VARCHAR(3000) NULL,
	CreatedOn VARCHAR(200) DEFAULT(GETDATE()),
	CreatedBy VARCHAR(200) DEFAULT(ORIGINAL_LOGIN())
)